services:
    backend:
        build:
            context: ./../../backend
            dockerfile: Dockerfile.dev
        container_name: backend
        ports:
            - "1234:80"
        volumes:
            - ./../../backend:/var/www/html
            - ./../../backend/storage:/var/www/html/storage
            - ./../../backend/bootstrap/cache:/var/www/html/bootstrap/cache
        environment:
              APP_ENV: '${APP_ENV:-local}'
              APP_KEY: '${APP_KEY}'
              GRUBCHAIN_ISS: 'grubchain'
              GRUBCHAIN_AUD: 'tokenizer'
              GRUBCHAIN_KID: 'gc-2025-key-1'
              GRUBCHAIN_SCOPE: 'pan_handle:issue'
              GRUBCHAIN_HMAC_SECRET: '/bmckvvJs3vOXVhq0GrcjEg6eKRvmBsnALIXqL9A+Gs='
              SECRET_PEM: "-----BEGIN PRIVATE KEY-----\nMIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQC6UHWcQVNzNzxz\nD7uDcu+PIS1kyAJXMmJ/CtqGCuee0dAJVWkB3CEf3IQ5qIfDAOwFqM6KQKCoL37i\nX94N5ArClYZ8/jO2Hq6wISe4Mh2ufbUQQMzdvsodrWVgHAv8RFhhyxLeDOK1k53O\nQg9HVPXd/07gCk5BUAJfeHdmt4h0i2wP9HkJAKqo8xUdXBtmQZGjt6D+P0aKCYIg\nbssbbvHjUsXQpteujHCmIhdd2C/uElWAecGTFAUqj62TX0fCxmrDGNSZGDTq+MKv\nZEenMaRp83PGisypRuEnQwqQr7PVNU1OtueInKmzHjU8UzBnbWCCAsmaTP2/Piuf\n6QQE6Zg9VaduHdaTmJVH7cQ39ZzYyZ77HLMkVU6Q3OPhwX8HclMarEHHL2PVWM/g\noVWYY7Mv80MkByTEYTN+YXgspFpujX8Wu/w2A7b/N9OVonVhHO4P/D39zLY4JqIX\n355B5dpA1awLrLg2L+aj3vE1Khx1eIgHs9WYsOwVIY2O5j4WY0yObc9CrnLUdM/i\n4QpqorWuvnc5h5t7y5MuzyKpK0BLrUWV8GEUvHks9TfGjWUdXnYc89g9GU1KBrbD\n7sW5Tb8VEjg2hy/CoLloXgphmPNFh45HFjn4anB0q9U0aOYmhG1W2/UnJr+JI1wo\nuIFQm6i4Q+tMVivYVq+0hZmwe4qeVwIDAQABAoICACWV97P3BcO3f+1iXhytgiBo\nvASZyMcYdgBVCzKBXqqOfx5y6YUjiFcqIE6VbhXryLF3lXsUgJSNSFaYqm448+a/\nTWtHyNzTocAMYDvreEtsNqu5ttqBE7sa8NmLrutMSlwoIH1FMjMZPXuPng9w10za\npWnTCmhooKHr5oKFQfTo73rkgcpMJSGCMF9E5o4haiUR9Vt1HmDYfDTYxQaawhdu\n6lMmZVpkIJGTTQ10gG7RqggKCAAIyOYGKCkTzqE/b+g9yR29YWeJmZTScRYMkLOD\nFncWJyV7FA7cmnQHzgqT/y2C/oBzwlRNIsYxrhEfYpm3wD3tjD8ZZqmS02m+SiS0\nmMODaNRNzGICMUBOqSx1r1mW5YyXFI6Dc6objTecl1kq9ljex5sD9AH8XMSvnGaK\ny2pT5jmxKmBATjXsL8eLFGNA8wOZP8C2xvuiYXTBdbh7wK0w6qDWnvoBnBWlYkfx\no5slc21MP9ppDKdXAAwxoUGy00RN3xHtWkg6zgVNB+InJ0GmHbvM633O0FSAVs6I\nP9ymymdbrJvdRFP57z/rt1ArAdtD5/MJE/RgZLzK+clcfpuJjD9+w9X/mw4pOG2S\neRnb6W0MkajdMYCgSxCbFzUIGV3lrjBvLzW5TLjmacEO1hPL5hgeI/+p0nJou3nX\n0Gd49tXugQI0TVw5VSVZAoIBAQD4k7g6DJm1o8aAtbPBGmvhjp3iuBBWzu/7Q0NV\n86Jga4YipqbKBEGjbH6hoPZxUNUe8PDaBx7hvoC2pgwfvdUnnnnA4ZzGgdcxdpKz\nT2bxYVh9jk0Oqj1QH2TPx7Co6eU6N8+GWQmlS6Q6IRhBDN6SOUIICwVWftDe5kvS\n5O5NYVgnHrKyNs1x6y+M3YTujcqJRU6C1LkeZL0yemAWMUcolsQQKWkVR2ODwZIk\n3dspmbLSkYk+in1PZ3e0/v6C3550ccWYtc+QvbdbTpnEiNjnvXMdPhekWfN4CG6x\n+gLJMnMNNRr7HYgfKfZ47IeIOpA1pV5a19ztwqkhtIvEsLHjAoIBAQC/4MOTgLYp\nVZ3g8KYXoTXhE9gemT8Bv6uR1Bg1xEzF3cmCUMGIle7q3mXiOGXWF83D4fMPDbL8\nhayA0C+w5qYpNsrEpksBxn8rBgstAwYtSHtwzMFsAjm+chzK51SzJvmSv9Ux66OX\nnVQqb8sMvVm356g32HTahqzLMrkwY1vhibcPQ7TsRZgqAFFOhMfLSe8vg5MFGsE9\n+sXEO1z2jq59EZL1dVY6QNo/+EISaxTm/ZixYJIyyjcE+AheZBQ5tyc/rTlSBEfL\nrPjP4PsMmBqZWiEv1PpBN2aDQPPxn3A2j39l+UDbpVWILEZjte4/6N5uduS4EuyI\nS56kDbfmPrv9AoIBAQDQJPmFehmXlEzaZ8vd7V7aX05rks7zsZIXpmoS5dBYxpBq\nIXvV+xxvWKDsfFj/57ydjQlQt9evFZK33nCWf6Gl7DhtPz3EpuJno68RgHJluqqb\nb/WsSvbOSYtjxQVzW287gZI/H/1IsP8SQbYKellAvbtB+uB8XfJOQy7IqDO3DcT/\n9N+TBPqg4ltNrAvsqUQoD6W/PZrJDXezde9Rhe/c1+nS0qoQTFfS8tqKDk+/FNk9\nIup2OQbW33/ISiEZu1/2h3H6/nqQ65tGVJnDjQd7fRKQMPchAsUxBHaUhxGgIaNf\nMtGl5kOePMgK15xhgRBSK2fHz6tKV87Bz2mdyIsbAoIBAQCoP3P+0OvqDrLjXOCm\n86sE85ucKRAAfor40htwefI/xhw98oXhOGdI9z4rQPy64CCDVIsGdiKuHqCGSwam\nfXjRxsPB73bx1ZYIqcH+9BnkdxwWatRn2wO7JOBuYq34cYKB1Ugh/9dwyHnWxDQt\ntZMIGU99uIWuYEz/2DheX6FfgJxN/DaWvueQXLruuKtgbDIZXav629z6dfwX912q\nrK3/6PsN1JeJePhnA08cS10GtvO/BUjs1DeuWbcs3WCGwzzdLw2GB07VH5UE4uf/\nwRgBw/A5uuy9ZtCy4q+E/SMuFGHHjun6L11yjDAkmpCQ5aa1AffIGH/jeztd6tGI\nSRYZAoIBADFnt8H2S79DfdLhYg7055e2omPGC4ruGK8B8lqEGhjDmTi+qlmUfv2N\nlL7tHRZ4XpATKIpMBaFudAKSys99FPFj+pWvQAmcY3dDBERqjl8I+VexKItbD+0m\ntctLaYbFDuKUNEZXGDWNymR+g3QDDK2kZq1ZU5WYVcoUefcZiuPs9HCqG1CWjhJC\nZ73UK5RcG58FHIn9coxeKDExSXoA4NIKJKC80GwgiSnXm6phzU4o7CeCEv94m2Da\nYz5QRtEoFOPqkurkejKdQwZQWxXc8nQG1FZsmnZuxkxp63XgFRV2eoViP7FJrvI9\n1Reg+YmbOObFJ/YbV5R+SZe8ua4VSPE=\n-----END PRIVATE KEY-----\n%"
        depends_on:
            - redis
            - mailpit
            - pgsql
        networks:
            - app

    frontend-csr:
        build:
            context: ./../../frontend
            dockerfile: Dockerfile.csr.dev
        container_name: frontend-csr
        profiles:
            - csr
        ports:
            - "5678:5678"
        volumes:
            - ./../../frontend:/app
            - /app/node_modules

        command: yarn dev:csr
        environment:
            VITE_API_URL_CLIENT: 'http://localhost:${API_PORT:-1234}'
        networks:
            - app
    frontend:
        build:
            context: ./../../frontend
            dockerfile: Dockerfile.ssr.dev
        container_name: frontend
        ports:
            - "5678:5678"
            - "24678:24678"
        volumes:
            - ./../../frontend:/app
            - /app/node_modules

        command: yarn dev:ssr
        environment:
            VITE_API_URL_CLIENT: '${API_URL_CLIENT}'
            VITE_API_URL_SERVER: '${API_URL_SERVER}'
            VITE_STRIPE_PUBLISHABLE_KEY: '${STRIPE_PUBLIC_KEY}'
            VITE_FRONTEND_URL: '${FRONTEND_URL}'
            VITE_APP_NAME: '${APP_NAME}'
            VITE_GRUBCHAIN_SECRET_KEY: '/bmckvvJs3vOXVhq0GrcjEg6eKRvmBsnALIXqL9A+Gs='
            VITE_GRUBCHAIN_ISS: 'grubchain'
            VITE_GRUBCHAIN_KID: 'gc-2025-key-1'
            VITE_GRUBCHAIN_AUD: 'tokenizer'
            VITE_GRUBCHAIN_SCOPE: 'pan_handle:issue'
            VITE_GRUBCHAIN_BUSINESS_ID: 'M1tADs'
            VITE_GRUBCHAIN_URL: 'https://staging.grubchain.xyz'
            VITE_GRUBCHAIN_TOKENIZER_URL: 'https://staging-tokenizer.grubchain.xyz/'
            VITE_GRUBCHAIN_PRIVACY: '/AREAPASSMARKETPLACEPRIVACYPOLICY.html'
            VITE_GRUBCHAIN_TOS: '/TermsofService.html'
            VITE_TOS_URL: '/TermsofService.html'
            VITE_PRIVACY_URL: '/AREAPASSMARKETPLACEPRIVACYPOLICY.html'
            VITE_CANCELATION_URL: '/CancellationandRefundPolicy.html'
            VITE_CHECKINS_RW: 'm1t3va'
            GRUBCHAIN_WEBHOOK_KEY: 'key123key123'
            APP_EMAIL_FOOTER_TEXT: '&copy; Areapass'
        networks:
            - app

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs:ro
        depends_on:
            - backend
            - frontend
        networks:
            - app

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'app-redis:/data'
        networks:
            - app
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - app
    pgsql:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'app-pgsql:/var/lib/postgresql/data'
        networks:
            - app
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: app
            MINIO_ROOT_PASSWORD: password
        volumes:
            - 'app-minio:/data/minio'
        networks:
            - app
        command: 'minio server /data/minio --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - curl
                - '-f'
                - 'http://localhost:9000/minio/health/live'
            retries: 3
            timeout: 5s

    createbuckets:
        image: minio/mc
        depends_on:
            - minio
        environment:
            MINIO_SERVER_URL: 'http://minio:9000'
            MINIO_ROOT_USER: 'app'
            MINIO_ROOT_PASSWORD: 'password'
        entrypoint: >
            /bin/sh -c "
            echo 'Waiting for MinIO to start...';
            until /usr/bin/mc alias set myminio $$MINIO_SERVER_URL $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD; do
                echo 'Waiting for MinIO server to become available...';
                sleep 1;
            done;
            echo 'MinIO started, configuring mc...';
            
            /usr/bin/mc alias set myminio $$MINIO_SERVER_URL $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
                        
            /usr/bin/mc mb myminio/hievents-public;
            /usr/bin/mc mb myminio/hievents-private;
            
            /usr/bin/mc anonymous set public myminio/hievents-public;
                        
            echo 'Buckets created and policies set.';
            exit 0;
            "
        networks:
            - app

networks:
    app:
        driver: bridge
volumes:
    app-redis:
        driver: local
    app-pgsql:
        driver: local
    app-minio:
        driver: local
