services:
    backend:
        build:
            context: ./../../backend
            dockerfile: Dockerfile.dev
        container_name: backend
        ports:
            - "1234:80"
        volumes:
            - ./../../backend:/var/www/html
            - ./../../backend/storage:/var/www/html/storage
            - ./../../backend/bootstrap/cache:/var/www/html/bootstrap/cache
        environment:
              APP_ENV: '${APP_ENV:-local}'
              APP_KEY: '${APP_KEY}'
              GRUBCHAIN_ISS: 'grubchain'
              GRUBCHAIN_AUD: 'tokenizer'
              GRUBCHAIN_KID: 'gc-2025-key-1'
              TOKENIZER_KID: 'gc-2025-key-1'
              GRUBCHAIN_SCOPE: 'pan_handle:issue'
              GRUBCHAIN_HMAC_SECRET: '/bmckvvJs3vOXVhq0GrcjEg6eKRvmBsnALIXqL9A+Gs='
              SECRET_PEM: "-----BEGIN PRIVATE KEY-----\nMIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCYlYH3cy2AgktB\n/Oh3oLHz9+jBOnXQVmpWH37gHU6tZi9A9TLdE5gbv8CBr+OjH0xURH0CTHfyrnQZ\nfUtezx0THaUEfnU1to3TfL4CR4tXCNJU9O8yAL8XVS20fKx3buh+PqoD/Yh0h3Yi\nKQTcNFXjS52sPK3BfZO0uY9HvdJm50s5SbQuovi4TPxzxDog3+Of8E9nTlt8eejk\n5wzpIHVBmd5ykEauY4dNHGw57UOUuwriP8gaP824lbDTfVM2L79t+am47aR4JFjq\nsmWAKj52xXoz1AHjzNG+vAnE7w26RB0zdSg2lKgJVaIshZW3yt5KNdQllQ3eQmFy\nbYmUggMezuxHvvwEcULF0cyc674jp2Uv8PDQLwgkY7hKSXWyD09cfcacCFtgEIZJ\nnk1a+CEQ2v6UT2uvpA2nVQG33W6lvNwFTpgpX1s6AK2sXuKSrSFpvdufa9a74lTI\nuUeO3z9s17AvrD5XLfBV39x5sre3sAVsPRFJ6pLYaWiie9uRHhTWs+S0kazy+PTV\njegEbgN4ekJgnt3Dgdjh3C+HLqpzv5IgaIhuiSjWDQMem73mhHYF/lLQLNiQO6MA\nurht2JGgPMwYS8tI8LyCqzt1nlqTcd131cmJZXxP+ZPa+7OlviM6chaA5C7X6dfd\nwhSIdb1DXPGiJIwwws9oJwz9qS8m3wIDAQABAoICAEkEvyHuZfeKIr6s64iYB6Dz\nYdjag5fUSuX1A4/3pneXn4Rr8s/WOSQKYvMM+5hL+YiYD+TCOGKT9q5eBewUnFrS\nBG6+n5O5TWzIVNudZkKbz5/laPRaZBgj5I/rW9N56VvE3DK1qQ/u5Wsaix9gEjwI\nKyfKD/K5CC7j3/vajK4/AIIlUctBpVn5SZSS8qhZzEH1S+JpnqFWa8vjAAwuQr7G\nhiv3/EMnERAnSml8MCukSOSV1kotf2LWi7zhzCjxt5/G6uA7JUpzRnPmNGmdja/j\n+AOGcPMVSMiIjvpF1iFtyDWgWsKn6DQzXT0GHmxKco877E6h4nWa+aw7XCwL/baK\nzXt1gN09MdT2cH63cI6yqa2yliQ89jRFqY2JVZJHbquQ+6NuN+1uiM/up0O49D1w\n5np2dcN65o0iCc1nuPvOb8VPNw5PClrHtOzW2KlH66Lgm5UEvszrO1sd8yZXyz78\na7KBkW7GHEgQJJsx6woPMByHr7+6Z3rtbUv7aX3ObA8uG+LKJfVsiynUMVYkeN49\nuewPYcXKQr4rS0zzr5PZiLRBuKAvTJqTJKu1K5B1fm5GCACh/MeptQxFiQ9P0Z8b\njdG2pbKiR5YCuJYbrM24W8ajr9Uvf9fkZYmHl8ujEoBD9QWM158ThQGuTjGfBW8h\nTL/RpA1B06wZbNOH1d3BAoIBAQDNWNY3i3UfSbfPXDMm2CHFRAchAHwSX0IYGtOh\nqPpZQem2KG/DGEEiB95yQfZyhz23OpvixwaZqkVLJlaNRboyJeHthxbT32jHjLUI\nXsouRepvpVUPgySr678/2bxc3qiCP2G8pZZDt0NTv5f55lj5i1BqdFhAKS7cHy+E\nufQ1zlx6X248X4c++CEAbLr5SoWiQTuKWtaFqVNkSeds911swAc0U9zo06RLSMsZ\n8pwqEvc/x+dwEf/WRBKFbVLp5LP32O0c+U4Ybr2L4jAx/5dEt30GUPWHkWC4D1ay\nktbhDJOioZ8fK3xRWu+STlS21V+SAAShFu81f3eHbxW6/kFBAoIBAQC+ONDfYpiA\nrs91CuXEmB5aS+Vbu6gZr1WooBxTJwk5FVRR2JK0Ud6T74+YCt4ADXpFrYEBfqr8\na/YrN9SSt/11nVR7QvlxrBFlqpmG4eF5/0vMJCG3YL1DJl/Jk1XVf0bIgOGdI3Ij\nHrfQ/ujxC0rFCaaLPa/eoqzrc/1CPWSBHgXO4CEqGpVdLntg+TzH7ZAmGVUZKl0x\nNKzQBEfj6bUA+1y3r4TdWqkG4Buq+ObulII0bc3SPni8m2dFdOxsOJs0eWefjP3B\nTcemfgQ/Ke/QEOZY2Rj0oUST6WH9R0r8RL9JTC3RVD/+HKSACcoHqrrtxUVapWEs\nyjh4VKzp1UAfAoIBAE+RJqArJ1zSQajVfvSENsGrFGATQgAUbRXN/0bapPbE9Xwh\nuvyLf2FiTy1Spd3GzYEb8p8yozoTofn2hv8Cj50y1JInEA9Ut9LqkJMHt6uqZ6aP\nF6CFHkaHeHmTMsuBcyXUzVg9iTX/4tSmnoq0WLGI68X0AuYJjyC37L+vFhNrPKYm\nKB64nT0nBBKYDvLdj15JjHqVrB3qeGeZw1STnN2wopoCDM0ihLyvHhOV0DD1XFyY\nZvMj5k/t3Idazw/WEG3u3iGl8D7DWirDoA0fjkuQFZ/G6vx2tlVbjCpxf1WAfAw+\nN9vqC6eyZrX4KBcYIon9+803h8Tg+T2/K1pjfoECggEAFuRhhrCn57yh7NT959Xi\nuT0vAgYoacbnCR8TqZImEv+VITBuH1NG9Qi8gDC2nM0CbQY/Yz2qOCyJ+JOEeo+3\n6gKgGyFpQZvSkCiix0/BwdvOdGfYwufafw1MM8cOal4h15ljDXUplD5rIrS6td+F\nBQdvSoyG8MUlCETyMpmO0dcaHdZtR1LhrNAeOwJjpS/azCr6ScgGZRiQv4v0VuJW\nTSLy+owd8kGp29D2o3HG4OlwbfzU6ztnblNJb1tt5Gw/iWYe6V2fYDcLEudRfYR/\nfsu53PFrhm0uAprwlvmQdaGUX67SSMHZ3av2xA3piVirnFfES+9hLXG8sAaItK9c\nQwKCAQB1dbCGdSGfXpabWmu1H83W0lX6Kl/H+Hu+zNmsTDbfwnwQK6q94TjzMilC\nOeJxg/vfQQff0GjprgBYnJ9GZ37P4k7DCiMOOm+1x2nnKKnXgNwrA0yNZTs2TY7l\n1vuK5y6kLoDLhYXRqjMtIDnuzZ3iHhHMyyt8b3Zi0P3QWmeLrx1TWY16/IU3oSOb\nKkl4Mms2O+5a2nthGw1Vep1ZN89T6NqRgyV9Uz0nbyfCySlM4yl/N5HzHHOWAQ2g\nsKiMYGBMjv44Hh/E2JJeC7bBYVVjhF2iJcWGgTr/flIetPBcfufMNacXyw1vs+Gz\nRjl1hbg9GY97u4z2hZZunE/HpJac\n-----END PRIVATE KEY-----\n"
        depends_on:
            - redis
            - mailpit
            - pgsql
        networks:
            - app

    frontend-csr:
        build:
            context: ./../../frontend
            dockerfile: Dockerfile.csr.dev
        container_name: frontend-csr
        profiles:
            - csr
        ports:
            - "5678:5678"
        volumes:
            - ./../../frontend:/app
            - /app/node_modules

        command: yarn dev:csr
        environment:
            VITE_API_URL_CLIENT: 'http://localhost:${API_PORT:-1234}'
        networks:
            - app
    frontend:
        build:
            context: ./../../frontend
            dockerfile: Dockerfile.ssr.dev
        container_name: frontend
        ports:
            - "5678:5678"
            - "24678:24678"
        volumes:
            - ./../../frontend:/app
            - /app/node_modules

        command: yarn dev:ssr
        environment:
            VITE_API_URL_CLIENT: '${API_URL_CLIENT}'
            VITE_API_URL_SERVER: '${API_URL_SERVER}'
            VITE_STRIPE_PUBLISHABLE_KEY: '${STRIPE_PUBLIC_KEY}'
            VITE_FRONTEND_URL: '${FRONTEND_URL}'
            VITE_APP_NAME: '${APP_NAME}'
            VITE_GRUBCHAIN_SECRET_KEY: '/bmckvvJs3vOXVhq0GrcjEg6eKRvmBsnALIXqL9A+Gs='
            VITE_GRUBCHAIN_ISS: 'grubchain'
            VITE_GRUBCHAIN_KID: 'gc-2025-key-1'
            VITE_GRUBCHAIN_AUD: 'tokenizer'
            VITE_GRUBCHAIN_SCOPE: 'pan_handle:issue'
            VITE_GRUBCHAIN_BUSINESS_ID: 'M1tADs'
            VITE_GRUBCHAIN_URL: 'https://beta.grubchain.xyz'
            VITE_GRUBCHAIN_TOKENIZER_URL: 'https://staging-tokenizer.grubchain.xyz/'
            VITE_GRUBCHAIN_PRIVACY: '/AREAPASSMARKETPLACEPRIVACYPOLICY.html'
            VITE_GRUBCHAIN_TOS: '/TermsofService.html'
            VITE_TOS_URL: '/TermsofService.html'
            VITE_PRIVACY_URL: '/AREAPASSMARKETPLACEPRIVACYPOLICY.html'
            VITE_CANCELATION_URL: '/CancellationandRefundPolicy.html'
            VITE_CHECKINS_RW: 'm1t3va'
            GRUBCHAIN_WEBHOOK_KEY: 'key123key123'
            APP_EMAIL_FOOTER_TEXT: '&copy; Areapass'
        networks:
            - app

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs:ro
        depends_on:
            - backend
            - frontend
        networks:
            - app

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'app-redis:/data'
        networks:
            - app
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - app
    pgsql:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'app-pgsql:/var/lib/postgresql/data'
        networks:
            - app
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: app
            MINIO_ROOT_PASSWORD: password
        volumes:
            - 'app-minio:/data/minio'
        networks:
            - app
        command: 'minio server /data/minio --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - curl
                - '-f'
                - 'http://localhost:9000/minio/health/live'
            retries: 3
            timeout: 5s

    createbuckets:
        image: minio/mc
        depends_on:
            - minio
        environment:
            MINIO_SERVER_URL: 'http://minio:9000'
            MINIO_ROOT_USER: 'app'
            MINIO_ROOT_PASSWORD: 'password'
        entrypoint: >
            /bin/sh -c "
            echo 'Waiting for MinIO to start...';
            until /usr/bin/mc alias set myminio $$MINIO_SERVER_URL $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD; do
                echo 'Waiting for MinIO server to become available...';
                sleep 1;
            done;
            echo 'MinIO started, configuring mc...';
            
            /usr/bin/mc alias set myminio $$MINIO_SERVER_URL $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
                        
            /usr/bin/mc mb myminio/hievents-public;
            /usr/bin/mc mb myminio/hievents-private;
            
            /usr/bin/mc anonymous set public myminio/hievents-public;
                        
            echo 'Buckets created and policies set.';
            exit 0;
            "
        networks:
            - app

networks:
    app:
        driver: bridge
volumes:
    app-redis:
        driver: local
    app-pgsql:
        driver: local
    app-minio:
        driver: local
