FROM node:alpine as build-stage

WORKDIR /app

RUN apk add --no-cache yarn

COPY package.json yarn.lock ./

COPY docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN yarn install

COPY . .

RUN yarn build

EXPOSE 5678

CMD ["/entrypoint.sh"]

