[supervisord]
nodaemon=true             ; stay in foreground (useful for containers)
logfile=/var/log/supervisord.log

[program:ssh_tunnel]
command=/usr/bin/autossh -M 0 -f 15432:$SSH_REMOTE_HOST:5432 ubuntu@$SSH_TUNNEL_HOST -i $SSH_TUNNEL_PEM
autostart=true
autorestart=true
startretries=999
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
environment=SSH_REMOTE_HOST="%(ENV_SSH_REMOTE_HOST)s",SSH_TUNNEL_USER="%(ENV_SSH_TUNNEL_USER)s",SSH_TUNNEL_PEM="%(ENV_SSH_TUNNEL_PEM)s"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
redirect_stderr=true
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
redirect_stderr=true
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

