name: Deploy to Heroku (container)
on:
  push:
    branches:
      - backend
      - frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app_name: areapass-api
            context: backend
            process: web
            dockerfile: backend/Dockerfile
          - app_name: areapass
            context: frontend
            process: web
            dockerfile: frontend/Dockerfile.csr
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Heroku login
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.context }}                 # 👈 per-service context
          file: ./${{ matrix.dockerfile }}
          push: true
          tags: registry.heroku.com/${{ matrix.app_name }}/${{ matrix.process }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Release
        run: |
          heroku container:release ${{ matrix.process }} -a ${{ matrix.app_name }}

